"""Added user's group

Revision ID: 04cd557eb83e
Revises: cd5916709a32
Create Date: 2026-01-17 23:42:08.097112

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04cd557eb83e"
down_revision: str | Sequence[str] | None = "cd5916709a32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("group_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "group_id")
    # ### end Alembic commands ###
