"""Removed 'id' primary key, 'user_id' is now primary key, added 'group_name' field

Revision ID: a66ca75c92dc
Revises: 04cd557eb83e
Create Date: 2026-03-02 20:52:56.874980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66ca75c92dc'
down_revision: Union[str, Sequence[str], None] = '04cd557eb83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_name', sa.String(length=15), nullable=True))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('users', 'group_name')
    # ### end Alembic commands ###
